#!/bin/sh
# Write <target-dir>/config.js from the VITE_* variables in the environment.
set -eu

TARGET_DIR="${1:?usage: gen-config.sh <target-dir>}"

echo "Generating runtime ${TARGET_DIR}/config.js from environment..."
{
    echo "// Generated by gen-config.sh. Do not edit."
    echo "window.__RUNTIME_CONFIG__ = {"
    for name in $(env | grep -E '^VITE_' | cut -d= -f1 | sort); do
        value=$(printenv "$name")
        # Escape values for JavaScript strings.
        escaped=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
        printf '  "%s": "%s",\n' "$name" "$escaped"
    done
    echo "};"
} > "${TARGET_DIR}/config.js"
