{{- if and .Values.db.enabled .Values.db.primary.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.dbServiceName" . }}-data
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.primary.persistence.size }}
  {{- with .Values.db.primary.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
