# Copyright (c) Humanitarian OpenStreetMap Team
#
# This file is part of OpenAerialMap.
#
#     OpenAerialMap is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenAerialMap is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenAerialMap.  If not, see <https:#www.gnu.org/licenses/>.
#

# List available commands
[private]
default:
  just --justfile {{justfile()}} --list prep

[no-cd]
_curl:
  #!/usr/bin/env bash
  if ! command -v curl &> /dev/null; then
      sudo apt-get update
      sudo apt-get install -y curl
  fi

# Install envsubst
[no-cd]
[no-exit-message]
_envsubst:
  #!/usr/bin/env bash
  just prep _curl

  # Get a8m/envsubst (required for default vals syntax ${VAR:-default})
  # Use local version, as envsubst may be installed on system already
  if [ -f ./envsubst ]; then
      echo "envsubst already exists. Continuing."
  else
      echo "Downloading a8m/envsubst"
      echo
      curl -L "https://github.com/a8m/envsubst/releases/download/v1.4.3/envsubst-$(uname -s)-$(uname -m)" -o envsubst
      chmod +x envsubst
  fi
