name: Build STAC Ingester

on:
  push:
    branches:
      - main
    paths:
      - "backend/stac-ingester/**"
      - "backend/stactools-hotosm/**"
  workflow_dispatch:

jobs:
  image-build-and-push:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.6.0
    with:
      context: backend/
      image_name: ghcr.io/${{ github.repository }}/stac-ingester
      build_target: prod
      dockerfile: stac-ingester/Dockerfile
