name: Build and Deploy STAC API Backend Service to Container Registry

on:
  push:
    branches:
      - main
    paths:
      - "backend/stac-api/**"
  workflow_dispatch:

jobs:
  image-build-and-push:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.5.1
    with:
      context: backend/stac-api/
      image_name: ghcr.io/${{ github.repository }}/stac-api
      build_target: prod
      dockerfile: Dockerfile
