# This workflow performs basic checks:
#
#   1. run a preparation step to install and cache node modules
#   2. once prep succeeds, lint and test run in parallel
#
# The checks only run on non-draft Pull Requests. They don't run on the main
# branch prior to deploy. It's recommended to use branch protection to avoid
# pushes straight to 'main'.

name: Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prep:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.4

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('frontend/package.json') }}

      - name: Install
        run: cd frontend && pnpm install

  lint:
    needs: prep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/.nvmrc"
          cache: "pnpm"

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('frontend/package.json') }}

      - name: Install
        run: cd frontend && pnpm install

      - name: Lint
        run: cd frontend && pnpm lint

  test:
    needs: prep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/.nvmrc"
          cache: "pnpm"

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('frontend/package.json') }}

      - name: Install
        run: cd frontend && pnpm install

      - name: Test
        run: cd frontend && pnpm test
