name: Deploy OAM UI to S3

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

  # Run every 2 months (approximately 60 days) at midnight UTC on the 1st
  schedule:
    - cron: "0 0 1 */2 *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# id-token required to get OIDC token for AWS
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: hotosm/gh-workflows/.github/workflows/just.yml@3.3.2
    with:
      environment: ${{ github.ref_name }}
      command: "deploy-frontend"
    secrets: inherit
